### ISSUE TITLE
Trouble building netlist generator

### ISSUE THREAD

**Issue by pgutwin** [daeyeon22/artificial_netlist_generator#10]
Hi Daeyeon - First, thank you for the great work on the netlist generator. Unfortunately I am having trouble building the application.

Specifically, I am getting CMAKE errors regarding "spdlog". Your original package did not include any find spdlog helper, so based on some examples I found, I put together a ```Findspdlog.cmake``` file. That cleared up some but not all the CMAKE errors, but I could have easily made a mistake in my implementation. My CMAKE log also contains gcc errors, but that could be related to the missing spdlog pointers.

I do not have much experience with CMAKE and my C development skills are dated, so it may be something super simple I'm doing wrong.

Thanks for any help you can provide!!

**Comment by daeyeon22** [comment]
Hi Paul –
I’m sorry that I don’t know how to solve the problem
I think there are mismatches in the version of submodules…
If you have still the problem even though you’ve already matched the version of submodules
Please check the dependency described in OpenROAD project.
My Cmake is based on https://github.com/The-OpenROAD-Project/OpenROAD
Thank you –


보낸 사람: Paul ***@***.***>
보낸 날짜: 2023년 5월 4일 목요일 오후 11:48
받는 사람: ***@***.***>
참조: ***@***.***>
제목: [daeyeon22/artificial_netlist_generator] Trouble building netlist generator (Issue #10)


Hi Daeyeon - First, thank you for the great work on the netlist generator. Unfortunately I am having trouble building the application.

Specifically, I am getting CMAKE errors regarding "spdlog". Your original package did not include any find spdlog helper, so based on some examples I found, I put together a Findspdlog.cmake file. That cleared up some but not all the CMAKE errors, but I could have easily made a mistake in my implementation. My CMAKE log also contains gcc errors, but that could be related to the missing spdlog pointers.

I do not have much experience with CMAKE and my C development skills are dated, so it may be something super simple I'm doing wrong.

Thanks for any help you can provide!!

**Comment by pgutwin** [comment]
Hi Daeyeon - thank you for your suggestion to check on the OpenROAD dependencies. That provided a good starting point for me. Subsequently learned that there are several quirks (problems) with my environment but I was able to eventually work around those.

I have successfully compiled the application and am now starting to explore using it. Thanks again for your help.
