### ISSUE TITLE
Do you have examples with open source lib such as ASAP7 or sky130

### ISSUE THREAD

**Issue by ravi-varadarajan** [daeyeon22/artificial_netlist_generator#2]
Hi Daeyeon

Thanks for putting ANG in opensource. I believe it will be really useful in creating test cases.   Can you upload some sample designs to github on opensource PDKs such as ASAP7 or sky13hd

-ravi

**Comment by daeyeon22** [comment]
Hi ravi,

I'll upload several test cases using asap7 soon.

we recognized seq logic based on whether the cell has any  'USE CLOCK' pin in LEF.

Thanks,
Daeyeon

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________
From: ravi-varadarajan ***@***.***>
Sent: Friday, March 3, 2023 6:02:55 AM
To: daeyeon22/artificial_netlist_generator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [daeyeon22/artificial_netlist_generator] Do you have examples with open source lib such as ASAP7 or sky130 (Issue #2)


Hi Daeyeon

Thanks for putting ANG in opensource. I believe it will be really useful in creating test cases. Can you upload some sample designs to github on opensource PDKs such as ASAP7 or sky13hd

-ravi

**Comment by ravi-varadarajan** [comment]
thanks...

**Comment by daeyeon22** [comment]
Please check the testcase uploaded.

**Comment by ravi-varadarajan** [comment]
Thanks  I can see test cases for both ASAP7 and nangate45
