### ISSUE TITLE
artnetgen_create_spec hangs

### ISSUE THREAD

**Issue by ravi-varadarajan** [daeyeon22/artificial_netlist_generator#4]
I am attaching a script I created for running on asap7. With this setup, artnetgen_create_spec is hanging   Is there anything I am doing wrong?

My cell_list.tcl uses all the cells in the lib (212 cells)

-thanks

  1 set lef_dir    /home/ravi/cong_home/OpenROAD-flow/OpenROAD-flow-scripts/flow/platforms/asap7/lef
  2 set lef_files          "$lef_dir/asap7_tech_1x_201209.lef $lef_dir/asap7sc7p5t_28_R_1x_220121a.lef"
  3 foreach lef $lef_files {
  4   read_lef $lef
  5 }
  6 set num_insts  10000
  7 set num_ios 100
  8 set comb_ratio 0.85
  9 set bbox 20
 10 set net_deg  3.0
 11 set path_depth  10
 12 source "cell_list.tcl"
 13 
 14 artnetgen_create_spec -num_insts $num_insts -num_primary_ios $num_ios -comb_ratio $comb_ratio -avg_bbox $bbox -avg_net_degree $net_deg -cell_list $cell_list -avg_to    po_order $path_depth -out_file ang.spec
 15 
 16 #generate_artificial_netlist -top_module top -spec_file ang.spec 
 17 
 18 #artnetgen_write_verilog -out_file ang.v 
 19 #artnetgen_write_sdc -out_file ang.sdc

**Comment by daeyeon22** [comment]
Please check the uploaded testcase

**Comment by ravi-varadarajan** [comment]
thanks for the uploaded test case.  I had a question on the only use cell list. If I do not have any constraints on the type of cells and the counts for each cell is there a default that I can use to specify all cells in the library

The only use cell list is useful to mimic a specific  design. However I want to truly create an artificial  netlist and am only interested in the parameters  (like num instances, net degree (important)  etc..)  can I do that without specifying the explicit cells to use?

**Comment by daeyeon22** [comment]
Yes, remove ONLYUSE SYNTAX.

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by ravi-varadarajan** [comment]
Do you mean  leave out   -cell_list ./onlyUseCell.list    in the call to artnetgen_create_spec?

When I leave out that option, I get a tcl error   as shown below

Finished LEF file:  /home/ravi/cong_home/OpenROAD-flow/OpenROAD-flow-scripts/flow/platforms/asap7/lef/asap7sc7p5t_28_R_1x_220121a.lef
Error: run_ang.tcl, 14 can't read "keys(-cell_list)": no such element in array

**Comment by ravi-varadarajan** [comment]
thanks for your help

**Comment by daeyeon22** [comment]
Remain the file and try to remove everylines in the file

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by ravi-varadarajan** [comment]
you mean give an empty file?

**Comment by daeyeon22** [comment]
Yes

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by ravi-varadarajan** [comment]
I am able to run the test case uploaded but my test case with ASAP7 is still hanging in create_spec

I am using the tech lef and std cell lef in  OpenROAD-flow-scripts /flow/platforms/asap7/lef area


asap7_tech_1x_201209.lef
asap7sc7p5t_28_R_1x_220121a.lef 

-ravi

**Comment by ravi-varadarajan** [comment]
If you can upload an example on asap7 with those lefs that would be great

**Comment by ravi-varadarajan** [comment]
Hi 

Were you able to run it with the asap7 libs that I was using?

**Comment by daeyeon22** [comment]
> 

Sure, I'm also making an example using asap7 now.
Give me several hours :)

**Comment by daeyeon22** [comment]
I’ve uploaded a testcase using ASAP7 right now.
Please check test/asap7

보낸 사람: ***@***.***>
보낸 날짜: 2023년 3월 5일 일요일 오전 2:00
받는 사람: ***@***.***>
참조: ***@***.***>; ***@***.***>
제목: Re: [daeyeon22/artificial_netlist_generator] artnetgen_create_spec hangs (Issue #4)


Hi

Were you able to run it with the asap7 libs that I was using?

**Comment by ravi-varadarajan** [comment]
thanks

**Comment by ravi-varadarajan** [comment]
Thanks I am able to run now
