### ISSUE TITLE
Some question about test_circuit.sdc

### ISSUE THREAD

**Issue by SaltyfishK423** [daeyeon22/artificial_netlist_generator#7]
Hi Daeyeon
Thanks for putting ANG in opensource. I used the ANG to generate some netlists, and I found that the values in the sdc file are all zeros. Meanwhile, I read your paper and found that you used the generated netlists to Place&Route for machine learning models. So I was wondering if you have any other methods to add timing constraints to the generated netlists for Place&Route.

**Comment by daeyeon22** [comment]
Hello,
There is nothing special to add timing constraints except for ‘create_clock’.
We assume that every IO delays are zero.
As you know, we define the clock period as <avg gate delay>*<avg timing depth>. If avg gate delay for target libs is 0.1ns and avg timing depth is 10, then the clock period becomes 0.1 * 10 ns =  1ns.
You can define <avg gate delay> using 'artnetgen_set_parameter -avg_gate_delay <value>'.
The default value of avg_gate_delay is 0.1 ns.
Thank you


보낸 사람: ***@***.***>
보낸 날짜: 2023년 3월 30일 목요일 오후 8:52
받는 사람: ***@***.***>
참조: ***@***.***>
제목: [daeyeon22/artificial_netlist_generator] Some question about test_circuit.sdc (Issue #7)


Hi Daeyeon
Thanks for putting ANG in opensource. I used the ANG to generate some netlists, and I found that the values in the sdc file are all zeros. Meanwhile, I read your paper and found that you used the generated netlists to Place&Route for machine learning models. So I was wondering if you have any other methods to add timing constraints to the generated netlists for Place&Route.

**Comment by SaltyfishK423** [comment]
Thanks for your anser!
